name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: MCCE4 Development Roadmap
          column: In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
